# -*- coding: utf-8 -*-
"""Beecrowd_1042.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukBXnzoVOSuEDfN0O-7FK9rsZa9YoZ2Z
"""

x = input().split()

a, b, c = x

a = int(a)
b = int(b)
c = int(c)

if a > b and b > c:
  print(f'{c}\n{b}\n{a}')
elif a > c and c > b:
  print(f'{b}\n{c}\n{a}')
elif a > b and a > c:
  print(f'{c}\n{b}\n{a}')
elif a > b and a > c:
  print(f'{c}\n{b}\n{a}')
elif a > b and a > c:
  print(f'{c}\n{b}\n{a}')
elif a > b and a > c:
  print(f'{c}\n{b}\n{a}')